@server=http://localhost:3000

### Post Ping (with params)

POST {{server}}/ping?host=8.8.8.8

### Post Ping (bad params)

POST {{server}}/ping?host=a.a.a.a

### Post Ping (without params)

POST {{server}}/ping
